#ifndef CEDAR_INPUT_KEY_H
#define CEDAR_INPUT_KEY_H

namespace Cedar
{
    enum class Key {
        backspace,
        tab,
        enter,
        shift,
        control,
        alt,
        pause,
        caps_lock,
        escape,
        space,
        page_up,
        page_down,
        end,
        home,
        left_arrow,
        up_arrow,
        right_arrow,
        down_arrow,
        select,
        print,
        execute,
        print_screen,
        insert,
        delete_key,
        help,

        d0,
        d1,
        d2,
        d3,
        d4,
        d5,
        d6,
        d7,
        d8,
        d9,

        a,
        b,
        c,
        d,
        e,
        f,
        g,
        h,
        i,
        j,
        k,
        l,
        m,
        n,
        o,
        p,
        q,
        r,
        s,
        t,
        u,
        v,
        w,
        x,
        y,
        z,
        
        left_windows,
        right_windows,
        applications,
        sleep,

        numpad_0,
        numpad_1,
        numpad_2,
        numpad_3,
        numpad_4,
        numpad_5,
        numpad_6,
        numpad_7,
        numpad_8,
        numpad_9,

        multiply,
        add,
        separator,
        subtract,
        decimal,
        divide,

        f1,
        f2,
        f3,
        f4,
        f5,
        f6,
        f7,
        f8,
        f9,
        f10,
        f11,
        f12,
        f13,
        f14,
        f15,
        f16,
        f17,
        f18,
        f19,
        f20,
        f21,
        f22,
        f23,
        f24,

        num_lock,
        scroll_lock,
        left_shift,
        right_shift,
        left_control,
        right_control,
        left_alt,
        right_alt,

        volume_mute,
        volume_down,
        volume_up,

        semicolon     /* ; */,
        equal         /* = */,
        comma         /* , */,
        minus         /* - */,
        period        /* . */,
        slash         /* / */,
        grave_accent  /* ` */,
        open_bracket  /* [ */,
        backslash     /* \ */,
        close_bracket /* ] */,
        apostrophe    /* ' */
    };
}

#endif // CEDAR_INPUT_KEY_H